Add missing -pthread flag
Fixes:

/usr/bin/ld: CMakeFiles/service-test.dir/__/service/glib-thread.cpp.o:
undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command
line