Add missing header
[...]/url-dispatcher/service/bad-url/exec-tool.cpp: In function ‘int main(int, char**)’:
[...]/url-dispatcher/service/bad-url/exec-tool.cpp:29:19: error: ‘runtime_error’ in namespace ‘std’ does not name a type
   29 |     } catch (std::runtime_error &e) {
      |                   ^~~~~~~~~~~~~